swagger: '2.0'
schemes:
  - https
basePath: /
host: httpbin.org
info:
  contact: 
    name: ""
    url: "http://httpbin.org"
  title: httpbin API
  description: 'A simple HTTP Request & Response Service'
  version: 0.9.2
paths:
  /anything:
    delete:
      produces:
        - application/json
      responses:
        '200':
          description: Anything passed in request
      summary: Returns anything passed in request data.
      tags:
        - Anything
    get:
      produces:
        - application/json
      responses:
        '200':
          description: Anything passed in request
      summary: Returns anything passed in request data.
      tags:
        - Anything
    patch:
      produces:
        - application/json
      responses:
        '200':
          description: Anything passed in request
      summary: Returns anything passed in request data.
      tags:
        - Anything
    post:
      produces:
        - application/json
      responses:
        '200':
          description: Anything passed in request
      summary: Returns anything passed in request data.
      tags:
        - Anything
    put:
      produces:
        - application/json
      responses:
        '200':
          description: Anything passed in request
      summary: Returns anything passed in request data.
      tags:
        - Anything
  '/anything/{anything}':
    parameters:
        - in: path
          name: anything
          type: string
          required: true
          description: anything
    delete:
      produces:
        - application/json
      responses:
        '200':
          description: Anything passed in request
      summary: Returns anything passed in request data.
      tags:
        - Anything
    get:
      produces:
        - application/json
      responses:
        '200':
          description: Anything passed in request
      summary: Returns anything passed in request data.
      tags:
        - Anything
    patch:
      produces:
        - application/json
      responses:
        '200':
          description: Anything passed in request
      summary: Returns anything passed in request data.
      tags:
        - Anything
    post:
      produces:
        - application/json
      responses:
        '200':
          description: Anything passed in request
      summary: Returns anything passed in request data.
      tags:
        - Anything
    put:
      produces:
        - application/json
      responses:
        '200':
          description: Anything passed in request
      summary: Returns anything passed in request data.
      tags:
        - Anything
    

definitions: {}
tags:
  - description: Returns anything that is passed to request
    name: Anything
